/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Tue Dec 17 13:37:16 2019. */

#include "FieldFile.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t FieldFile_fields[3] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, FieldFile, unitDistance, unitDistance, 0),
    PB_FIELD(  2, FLOAT   , REPEATED, CALLBACK, OTHER, FieldFile, data, unitDistance, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
