/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Fri Jun 12 23:42:54 2020. */

#include "Replay.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ReplayFrame_fields[15] = {
    PB_FIELD(  1, UINT32  , SINGULAR, STATIC  , FIRST, ReplayFrame, timestamp, timestamp, 0),
    PB_FIELD(  2, UINT32  , SINGULAR, STATIC  , OTHER, ReplayFrame, frameIdx, timestamp, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, STATIC  , OTHER, ReplayFrame, robots, frameIdx, &RDRobot_fields),
    PB_FIELD(  4, INT32   , SINGULAR, STATIC  , OTHER, ReplayFrame, localiserEvals, robots, 0),
    PB_FIELD(  5, MESSAGE , SINGULAR, STATIC  , OTHER, ReplayFrame, ballPos, localiserEvals, &RDPointF_fields),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, ReplayFrame, localiserRate, ballPos, 0),
    PB_FIELD(  7, MESSAGE , SINGULAR, STATIC  , OTHER, ReplayFrame, yellowGoalPos, localiserRate, &RDPointF_fields),
    PB_FIELD(  8, MESSAGE , SINGULAR, STATIC  , OTHER, ReplayFrame, blueGoalPos, yellowGoalPos, &RDPointF_fields),
    PB_FIELD(  9, BOOL    , SINGULAR, STATIC  , OTHER, ReplayFrame, isYellowKnown, blueGoalPos, 0),
    PB_FIELD( 10, BOOL    , SINGULAR, STATIC  , OTHER, ReplayFrame, isBallKnown, isYellowKnown, 0),
    PB_FIELD( 11, BOOL    , SINGULAR, STATIC  , OTHER, ReplayFrame, isBlueKnown, isBallKnown, 0),
    PB_FIELD( 12, MESSAGE , SINGULAR, STATIC  , OTHER, ReplayFrame, goalEstimate, isBlueKnown, &RDPointF_fields),
    PB_FIELD( 13, MESSAGE , SINGULAR, STATIC  , OTHER, ReplayFrame, estimateMinBounds, goalEstimate, &RDPointF_fields),
    PB_FIELD( 14, MESSAGE , SINGULAR, STATIC  , OTHER, ReplayFrame, estimateMaxBounds, estimateMinBounds, &RDPointF_fields),
    PB_LAST_FIELD
};

const pb_field_t ReplayFile_fields[4] = {
    PB_FIELD(  1, INT32   , SINGULAR, STATIC  , FIRST, ReplayFile, frameWidth, frameWidth, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, ReplayFile, frameHeight, frameWidth, 0),
    PB_FIELD(  3, MESSAGE , REPEATED, CALLBACK, OTHER, ReplayFile, frames, frameHeight, &ReplayFrame_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ReplayFrame, robots[0]) < 65536 && pb_membersize(ReplayFrame, ballPos) < 65536 && pb_membersize(ReplayFrame, yellowGoalPos) < 65536 && pb_membersize(ReplayFrame, blueGoalPos) < 65536 && pb_membersize(ReplayFrame, goalEstimate) < 65536 && pb_membersize(ReplayFrame, estimateMinBounds) < 65536 && pb_membersize(ReplayFrame, estimateMaxBounds) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_ReplayFrame_ReplayFile)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(ReplayFrame, robots[0]) < 256 && pb_membersize(ReplayFrame, ballPos) < 256 && pb_membersize(ReplayFrame, yellowGoalPos) < 256 && pb_membersize(ReplayFrame, blueGoalPos) < 256 && pb_membersize(ReplayFrame, goalEstimate) < 256 && pb_membersize(ReplayFrame, estimateMinBounds) < 256 && pb_membersize(ReplayFrame, estimateMaxBounds) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_ReplayFrame_ReplayFile)
#endif


/* @@protoc_insertion_point(eof) */
