/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Mon Jul 13 23:03:26 2020. */

#ifndef PB_REPLAY_PB_H_INCLUDED
#define PB_REPLAY_PB_H_INCLUDED
#include <pb.h>

#include "RemoteDebug.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _ReplayFile {
    int32_t frameWidth;
    int32_t frameHeight;
    pb_callback_t frames;
/* @@protoc_insertion_point(struct:ReplayFile) */
} ReplayFile;

typedef struct _ReplayFrame {
    uint32_t timestamp;
    uint32_t frameIdx;
    pb_size_t robots_count;
    RDRobot robots[2];
    int32_t localiserEvals;
    RDPointF ballPos;
    int32_t localiserRate;
    RDPointF yellowGoalPos;
    RDPointF blueGoalPos;
    bool isYellowKnown;
    bool isBallKnown;
    bool isBlueKnown;
    RDPointF goalEstimate;
    RDPointF estimateMinBounds;
    RDPointF estimateMaxBounds;
/* @@protoc_insertion_point(struct:ReplayFrame) */
} ReplayFrame;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ReplayFrame_init_default                 {0, 0, 0, {RDRobot_init_default, RDRobot_init_default}, 0, RDPointF_init_default, 0, RDPointF_init_default, RDPointF_init_default, 0, 0, 0, RDPointF_init_default, RDPointF_init_default, RDPointF_init_default}
#define ReplayFile_init_default                  {0, 0, {{NULL}, NULL}}
#define ReplayFrame_init_zero                    {0, 0, 0, {RDRobot_init_zero, RDRobot_init_zero}, 0, RDPointF_init_zero, 0, RDPointF_init_zero, RDPointF_init_zero, 0, 0, 0, RDPointF_init_zero, RDPointF_init_zero, RDPointF_init_zero}
#define ReplayFile_init_zero                     {0, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define ReplayFile_frameWidth_tag                1
#define ReplayFile_frameHeight_tag               2
#define ReplayFile_frames_tag                    3
#define ReplayFrame_timestamp_tag                1
#define ReplayFrame_frameIdx_tag                 2
#define ReplayFrame_robots_tag                   3
#define ReplayFrame_localiserEvals_tag           4
#define ReplayFrame_ballPos_tag                  5
#define ReplayFrame_localiserRate_tag            6
#define ReplayFrame_yellowGoalPos_tag            7
#define ReplayFrame_blueGoalPos_tag              8
#define ReplayFrame_isYellowKnown_tag            9
#define ReplayFrame_isBallKnown_tag              10
#define ReplayFrame_isBlueKnown_tag              11
#define ReplayFrame_goalEstimate_tag             12
#define ReplayFrame_estimateMinBounds_tag        13
#define ReplayFrame_estimateMaxBounds_tag        14

/* Struct field encoding specification for nanopb */
extern const pb_field_t ReplayFrame_fields[15];
extern const pb_field_t ReplayFile_fields[4];

/* Maximum encoded size of messages (where known) */
#define ReplayFrame_size                         282
/* ReplayFile_size depends on runtime parameters */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define REPLAY_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
