/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Mon Mar  9 20:59:04 2020. */

#ifndef PB_UART_PB_H_INCLUDED
#define PB_UART_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _ESP32DebugCommand {
    int32_t msgId;
    int32_t robotId;
    int32_t orientation;
    int32_t x;
    int32_t y;
/* @@protoc_insertion_point(struct:ESP32DebugCommand) */
} ESP32DebugCommand;

typedef struct _LocalisationData {
    float estimatedX;
    float estimatedY;
/* @@protoc_insertion_point(struct:LocalisationData) */
} LocalisationData;

typedef struct _MouseData {
    int32_t relDspX;
    int32_t relDspY;
    int32_t absDspX;
    int32_t absDspY;
/* @@protoc_insertion_point(struct:MouseData) */
} MouseData;

typedef struct _ObjectData {
    float ballAngle;
    float ballMag;
    bool ballExists;
    float goalBlueAngle;
    float goalBlueMag;
    bool goalBlueExists;
    float goalYellowAngle;
    float goalYellowMag;
    bool goalYellowExists;
/* @@protoc_insertion_point(struct:ObjectData) */
} ObjectData;

/* Default values for struct fields */

/* Initializer values for message structs */
#define ObjectData_init_default                  {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define LocalisationData_init_default            {0, 0}
#define MouseData_init_default                   {0, 0, 0, 0}
#define ESP32DebugCommand_init_default           {0, 0, 0, 0, 0}
#define ObjectData_init_zero                     {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define LocalisationData_init_zero               {0, 0}
#define MouseData_init_zero                      {0, 0, 0, 0}
#define ESP32DebugCommand_init_zero              {0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define ESP32DebugCommand_msgId_tag              1
#define ESP32DebugCommand_robotId_tag            2
#define ESP32DebugCommand_orientation_tag        3
#define ESP32DebugCommand_x_tag                  4
#define ESP32DebugCommand_y_tag                  5
#define LocalisationData_estimatedX_tag          1
#define LocalisationData_estimatedY_tag          2
#define MouseData_relDspX_tag                    1
#define MouseData_relDspY_tag                    2
#define MouseData_absDspX_tag                    3
#define MouseData_absDspY_tag                    4
#define ObjectData_ballAngle_tag                 1
#define ObjectData_ballMag_tag                   2
#define ObjectData_ballExists_tag                3
#define ObjectData_goalBlueAngle_tag             4
#define ObjectData_goalBlueMag_tag               5
#define ObjectData_goalBlueExists_tag            6
#define ObjectData_goalYellowAngle_tag           7
#define ObjectData_goalYellowMag_tag             8
#define ObjectData_goalYellowExists_tag          9

/* Struct field encoding specification for nanopb */
extern const pb_field_t ObjectData_fields[10];
extern const pb_field_t LocalisationData_fields[3];
extern const pb_field_t MouseData_fields[5];
extern const pb_field_t ESP32DebugCommand_fields[6];

/* Maximum encoded size of messages (where known) */
#define ObjectData_size                          36
#define LocalisationData_size                    10
#define MouseData_size                           44
#define ESP32DebugCommand_size                   55

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define UART_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
