/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Sat Aug 03 16:00:17 2019. */

#include "i2c.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SensorUpdate_fields[11] = {
    PB_FIELD(  1, FLOAT   , SINGULAR, STATIC  , FIRST, SensorUpdate, tsopAngle, tsopAngle, 0),
    PB_FIELD(  2, FLOAT   , SINGULAR, STATIC  , OTHER, SensorUpdate, tsopStrength, tsopAngle, 0),
    PB_FIELD(  3, FLOAT   , SINGULAR, STATIC  , OTHER, SensorUpdate, lineAngle, tsopStrength, 0),
    PB_FIELD(  4, FLOAT   , SINGULAR, STATIC  , OTHER, SensorUpdate, lineSize, lineAngle, 0),
    PB_FIELD(  5, BOOL    , SINGULAR, STATIC  , OTHER, SensorUpdate, onLine, lineSize, 0),
    PB_FIELD(  6, BOOL    , SINGULAR, STATIC  , OTHER, SensorUpdate, lineOver, onLine, 0),
    PB_FIELD(  7, FLOAT   , SINGULAR, STATIC  , OTHER, SensorUpdate, lastAngle, lineOver, 0),
    PB_FIELD(  8, FLOAT   , SINGULAR, STATIC  , OTHER, SensorUpdate, heading, lastAngle, 0),
    PB_FIELD(  9, INT32   , SINGULAR, STATIC  , OTHER, SensorUpdate, temperature, heading, 0),
    PB_FIELD( 10, FLOAT   , SINGULAR, STATIC  , OTHER, SensorUpdate, voltage, temperature, 0),
    PB_LAST_FIELD
};

const pb_field_t I2CSlaveProvide_fields[7] = {
    PB_FIELD(  1, FLOAT   , SINGULAR, STATIC  , FIRST, I2CSlaveProvide, lineAngle, lineAngle, 0),
    PB_FIELD(  2, FLOAT   , SINGULAR, STATIC  , OTHER, I2CSlaveProvide, lineSize, lineAngle, 0),
    PB_FIELD(  3, BOOL    , SINGULAR, STATIC  , OTHER, I2CSlaveProvide, onLine, lineSize, 0),
    PB_FIELD(  4, BOOL    , SINGULAR, STATIC  , OTHER, I2CSlaveProvide, lineOver, onLine, 0),
    PB_FIELD(  5, FLOAT   , SINGULAR, STATIC  , OTHER, I2CSlaveProvide, lastAngle, lineOver, 0),
    PB_FIELD(  6, FLOAT   , SINGULAR, STATIC  , OTHER, I2CSlaveProvide, heading, lastAngle, 0),
    PB_LAST_FIELD
};

const pb_field_t I2CMasterProvide_fields[5] = {
    PB_FIELD(  1, FLOAT   , SINGULAR, STATIC  , FIRST, I2CMasterProvide, direction, direction, 0),
    PB_FIELD(  2, FLOAT   , SINGULAR, STATIC  , OTHER, I2CMasterProvide, orientation, direction, 0),
    PB_FIELD(  3, FLOAT   , SINGULAR, STATIC  , OTHER, I2CMasterProvide, speed, orientation, 0),
    PB_FIELD(  4, FLOAT   , SINGULAR, STATIC  , OTHER, I2CMasterProvide, heading, speed, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
