# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FieldFile.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='FieldFile.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x46ieldFile.proto\"k\n\tFieldFile\x12\x14\n\x0cunitDistance\x18\x01 \x01(\x05\x12\x11\n\tcellCount\x18\x02 \x01(\x05\x12\x12\n\nfieldWidth\x18\x03 \x01(\x05\x12\x13\n\x0b\x66ieldHeight\x18\x04 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x05 \x03(\x02\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_FIELDFILE = _descriptor.Descriptor(
  name='FieldFile',
  full_name='FieldFile',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unitDistance', full_name='FieldFile.unitDistance', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cellCount', full_name='FieldFile.cellCount', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fieldWidth', full_name='FieldFile.fieldWidth', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fieldHeight', full_name='FieldFile.fieldHeight', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='FieldFile.data', index=4,
      number=5, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=126,
)

DESCRIPTOR.message_types_by_name['FieldFile'] = _FIELDFILE

FieldFile = _reflection.GeneratedProtocolMessageType('FieldFile', (_message.Message,), dict(
  DESCRIPTOR = _FIELDFILE,
  __module__ = 'FieldFile_pb2'
  # @@protoc_insertion_point(class_scope:FieldFile)
  ))
_sym_db.RegisterMessage(FieldFile)


# @@protoc_insertion_point(module_scope)
