/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.4 at Sat Dec 21 19:40:04 2019. */

#include "i2c.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t I2CSlaveProvide_fields[11] = {
    PB_FIELD(  1, FLOAT   , SINGULAR, STATIC  , FIRST, I2CSlaveProvide, lineAngle, lineAngle, 0),
    PB_FIELD(  2, FLOAT   , SINGULAR, STATIC  , OTHER, I2CSlaveProvide, lineSize, lineAngle, 0),
    PB_FIELD(  3, BOOL    , SINGULAR, STATIC  , OTHER, I2CSlaveProvide, onLine, lineSize, 0),
    PB_FIELD(  4, BOOL    , SINGULAR, STATIC  , OTHER, I2CSlaveProvide, lineOver, onLine, 0),
    PB_FIELD(  5, FLOAT   , SINGULAR, STATIC  , OTHER, I2CSlaveProvide, lastAngle, lineOver, 0),
    PB_FIELD(  6, INT32   , SINGULAR, STATIC  , OTHER, I2CSlaveProvide, frontLRF, lastAngle, 0),
    PB_FIELD(  7, INT32   , SINGULAR, STATIC  , OTHER, I2CSlaveProvide, rightLRF, frontLRF, 0),
    PB_FIELD(  8, INT32   , SINGULAR, STATIC  , OTHER, I2CSlaveProvide, backLRF, rightLRF, 0),
    PB_FIELD(  9, INT32   , SINGULAR, STATIC  , OTHER, I2CSlaveProvide, leftLRF, backLRF, 0),
    PB_FIELD( 10, FLOAT   , SINGULAR, STATIC  , OTHER, I2CSlaveProvide, heading, leftLRF, 0),
    PB_LAST_FIELD
};

const pb_field_t I2CMasterProvide_fields[2] = {
    PB_FIELD(  1, FLOAT   , SINGULAR, STATIC  , FIRST, I2CMasterProvide, heading, heading, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
