/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.4 at Sat Dec 21 19:40:04 2019. */

#ifndef PB_I2C_PB_H_INCLUDED
#define PB_I2C_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _I2CMasterProvide {
    float heading;
/* @@protoc_insertion_point(struct:I2CMasterProvide) */
} I2CMasterProvide;

typedef struct _I2CSlaveProvide {
    float lineAngle;
    float lineSize;
    bool onLine;
    bool lineOver;
    float lastAngle;
    int32_t frontLRF;
    int32_t rightLRF;
    int32_t backLRF;
    int32_t leftLRF;
    float heading;
/* @@protoc_insertion_point(struct:I2CSlaveProvide) */
} I2CSlaveProvide;

/* Default values for struct fields */

/* Initializer values for message structs */
#define I2CSlaveProvide_init_default             {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define I2CMasterProvide_init_default            {0}
#define I2CSlaveProvide_init_zero                {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define I2CMasterProvide_init_zero               {0}

/* Field tags (for use in manual encoding/decoding) */
#define I2CMasterProvide_heading_tag             1
#define I2CSlaveProvide_lineAngle_tag            1
#define I2CSlaveProvide_lineSize_tag             2
#define I2CSlaveProvide_onLine_tag               3
#define I2CSlaveProvide_lineOver_tag             4
#define I2CSlaveProvide_lastAngle_tag            5
#define I2CSlaveProvide_frontLRF_tag             6
#define I2CSlaveProvide_rightLRF_tag             7
#define I2CSlaveProvide_backLRF_tag              8
#define I2CSlaveProvide_leftLRF_tag              9
#define I2CSlaveProvide_heading_tag              10

/* Struct field encoding specification for nanopb */
extern const pb_field_t I2CSlaveProvide_fields[11];
extern const pb_field_t I2CMasterProvide_fields[2];

/* Maximum encoded size of messages (where known) */
#define I2CSlaveProvide_size                     68
#define I2CMasterProvide_size                    5

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define I2C_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
