site_name: Team Omicron
theme: material
site_description: "Documentation website for Team Omicron from BBC Robotics, competing in the RoboCup Jr 2020 Internationals."
copyright: "Copyright (c) 2020 Team Omicron."

nav:
    - Home: index.md
    - About: about.md
    - Hardware:
        - Structural design: structural_design.md
        - Electrical design: electrical_design.md
    - Software:
        - Omicam (vision and localisastion): omicam.md
        - Omicontrol (debugging and control): omicontrol.md
        - Game strategies: strategy.md
        - Protocol Buffers: protobuf.md
    - Open source acknowledgement: open_source.md

plugins:
    - search

markdown_extensions:
    - footnotes
    - smarty
