site_name: Team Omicron
theme: material
site_description: "Documentation website for Team Omicron, an open-source RoboCup Jr Open Soccer team from Brisbane Boys' College."
copyright: Copyright (c) 2020 Team Omicron. Documentation is under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

nav:
    - Home: index.md
    - About: about.md
    - Hardware:
        - Structural design: structural_design.md
        - Electrical design: electrical_design.md
        - SBC & Camera: sbc.md
    - Software:
        - Our open-source release!: open_source_release.md
        - Omicam: omicam.md
        - Omicontrol: omicontrol.md
        - Game strategies: strategy.md
        - Protocol Buffers: protobuf.md
        - Finite State Machine: fsm.md
        - Low-level code: lowlevel.md
        - Open source:
            - Third party libraries: open_source.md

plugins:
    - search

markdown_extensions:
    - footnotes
    - smarty
