site_name: Team Omicron
theme: material
site_description: "Documentation website for Team Omicron from BBC Robotics, competing in the RoboCup Jr 2020 Internationals."
copyright: "Copyright (c) 2020 Team Omicron."

nav:
    - Home: index.md
    - About: about.md
    - Hardware:
        - Structural design: structural_design.md
        - Electrical design: electrical_design.md
        - SBC: sbc.md
    - Software:
        - Omicam: omicam.md
        - Omicontrol: omicontrol.md
        - Game strategies: strategy.md
        - Protocol Buffers: protobuf.md
        - Finite State Machine: fsm.md
        - Low-level code: lowlevel.md
        - Open source info: open_source.md

plugins:
    - search

markdown_extensions:
    - footnotes
    - smarty
